
import edept from '@assets/images/store/edept.svg?sprite';


export default [{
  name: '建筑能耗管理',
  icon: edept,
  description: '根据国家机关办公建筑和大型公共建筑能耗监测系统、高等学校校园建筑节能监管系统等相关导则和《绿色建筑评价标准》，对建筑的水、电、气、热等能耗数据进行实时采集与监测，实现能源分类、分项（空调/照明/动力/其他）和分户计量。系统在采集数据的基础上，通过综合计算、对比分析等方式，提供更具业务价值的可视化数据，协助能源管理部门科学决策、加强管理，是搭建建筑节能、设施运管等系统平台的基础。'
}, {
  name: '部门能耗管理',
  icon: edept,
  description: '根据国家机关办公建筑和大型公共建筑能耗监测系统、高等学校校园建筑节能监管系统等相关导则和《绿色建筑评价标准》，对建筑的水、电、气、热等能耗数据进行实时采集与监测，实现能源分类、分项（空调/照明/动力/其他）和分户计量。系统在采集数据的基础上，通过综合计算、对比分析等方式，提供更具业务价值的可视化数据，协助能源管理部门科学决策、加强管理，是搭建建筑节能、设施运管等系统平台的基础。'
}, {
  name: '设施能耗管理',
  icon: edept,
  description: '根据国家机关办公建筑和大型公共建筑能耗监测系统、高等学校校园建筑节能监管系统等相关导则和《绿色建筑评价标准》，对建筑的水、电、气、热等能耗数据进行实时采集与监测，实现能源分类、分项（空调/照明/动力/其他）和分户计量。系统在采集数据的基础上，通过综合计算、对比分析等方式，提供更具业务价值的可视化数据，协助能源管理部门科学决策、加强管理，是搭建建筑节能、设施运管等系统平台的基础。'
}, {
  name: '用能账目管理',
  icon: edept
}, {
  name: '用能平衡检测',
  icon: edept
}, {
  name: '能耗数据上报',
  icon: edept
}, {
  name: '宿舍用能收费',
  icon: edept
}, {
  name: '商业用能收费',
  icon: edept
}, {
  name: '充电运营收费',
  icon: edept
}, {
  name: '热水运营收费',
  icon: edept
}, {
  name: '自助取水收费',
  icon: edept
}, {
  name: '智能空调监控',
  icon: edept
}, {
  name: '智能照明监控',
  icon: edept
}, {
  name: '雨水回用监控',
  icon: edept
}, {
  name: '供暖节能监控',
  icon: edept
}, {
  name: '配变电所监管',
  icon: edept
}, {
  name: '电气火灾监管',
  icon: edept
}, {
  name: '二次泵房监管',
  icon: edept
}, {
  name: '给水管网监管',
  icon: edept
}, {
  name: '电梯运行监管',
  icon: edept
}, {
  name: '消防安全监管',
  icon: edept
}, {
  name: '井盖安全监管',
  icon: edept
}, {
  name: '智慧物联组网',
  icon: edept
}, {
  name: '运行调度中心',
  icon: edept
}, {
  name: '能源智慧管家',
  icon: edept
}, {
  name: '聚合定制空间',
  icon: edept
}];
