<div>
  <h2>
    智能网由TR1000系列
  </h2>
  <p>适用于各类需要统一数据格式上报的场合，支持BACnet/IP、OPC和Modbus/TCP等协议，支持更多传统产业如智能楼宇、工业自控等，向智能化物联网方向升级。</p>
  <ul>
    <li>
    BACNet、ModbusTCP、OPC格式数据转换
    </li>
    <li>
    统一数据上报格式
    </li>
    <li>
    提供网关及其连接设备远程状态诊断
    </li>
  </ul>
</div>